Company: michaelcychan-org
Application: Coauthor
ProductDescription: |
  Product Description Line 1
  Product Description Line 2
  test pull request
Market:
  - EU
  - UK
BugTrackingProjectLink: https://github.com/orgs/michaelcychan-org/projects/4
SoftwareClassification:
  Questions:
    HazardousSituationPossible: false
  SafetyClass: A
  Rationale: |
    This is a class A rationale
    This is a class A rationale
TestingTools:
  SystemTesting:
    - Selenium
    - Cypress
    - Cucumber
  SecurityTesting:
    - ZAP
    - Burp
  CompatabilityTesting:
    - BrowserStack
    - SauceLabs
