Company: michaelcychan-org
Application: Coauthor
ProductDescription: |
  Product Description Line 1guyg uu
  Product Description Line 2adsfa
TestingTools:
  SystemTesting:
    - Selenium
    - Cypress
    - Cucumber
  SecurityTesting:
    - ZAP
    - Burp
  CompatabilityTesting:
    - BrowserStack
    - SauceLabs
Roles:
  Management:
    Lead: michaelcychan
    Members:
      - michaelcychan
      - michaelchansecond
  QARA:
    Lead: michaelcychan
    Members:
      - michaelcychan
      - michaelchansecond
  SWDevelopment:
    Lead: michaelcychan
    Members:
      - michaelcychan-org/michaelcychan-org-team
  Clinical:
    Lead: michaelchansecond
    Members:
      - michaelcychan-org/michaelcychan-org-team
