Company: michaelcychan-org
Application: Coauthor
ProductDescription: |
  Product Description Line 1
  Product Description Line 2
Market:
  - EU
  - UK
BugTrackingProjectLink: https://github.com/orgs/michaelcychan-org/projects/1
SoftwareClassification:
  Questions:
    HazardousSituationPossible: false
  SafetyClass: A
  Rationale: |
    This is a class A rationale
    Line 2  
    Line 3
TestingTools:
  SystemTesting:
    - Selenium
    - Cypress
    - Cucumber
  SecurityTesting:
    - ZAP
    - Burp
  CompatabilityTesting:
    - BrowserStack
    - SauceLabs
Roles:
  Management:
    Lead: michaelcychan
    Members:
      - michaelcychan
      - michaelchansecond
  QARA:
    Lead: michaelcychan
    Members:
      - michaelcychan
      - michaelchansecond
  SWDevelopment:
    Lead: michaelcychan
    Members:
      - michaelcychan-org/michaelcychan-org-team
  Clinical:
    Lead: michaelchansecond
    Members:
      - michaelcychan-org/michaelcychan-org-team
