Company: Hindsight
Application: Coauthor
ProductDescription: |
  We have launched
  Let's get more features - architecture.yaml
  and more users
ExtraKey: 'Random Value'
Market:
  - EU
  - UK
SoftwareClassification:
  Questions:
    HazardousSituationPossible: false
  SafetyClass: A
  Rationale: |
    This is a class A rationale
    This is a class A rationale
TestingTools:
  SystemTesting:
    - Selenium
    - Cypress
    - Cucumber
  SecurityTesting:
    - ZAP
    - Burp
  CompatabilityTesting:
    - BrowserStack
    - SauceLabs
Roles:
  # Please add/change GitHub usernames to the following roles
  Management:
    Lead: michaelcychan
    Members:
      - michaelcychan
  SWDevelopment:
    Lead: michaelcychan
    Members:
      - michaelcychan
  Clinical:
    Lead: michaelcychan
    Members:
      - michaelcychan
  QARA:
    Lead: michaelcychan
    Members:
      - michaelcychan
SDLC:
  IssueTracking:
    Provider: "GitHub"
    TrackingProjectLink: replace-me-with-bug-tracking-project-link
  BranchingStrategy: "Feature Branching"
  CommitMessageFormat: "Conventional Commits"
  Methodology: "SCRUM"
  IterationLength: 2
Security:
  PenetrationTesting:
    Required: true
    Frequency: "Quarterly"
  SAST:
    Frequency: Every Build
    Tools:
      - Tool 1
      - Tool 2
  SBOM:
    GenerationTools:
      - Tool A
      - Tool B
    MonitoringTools:
      - Tool C
    Frequency: Every Build
