on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  upload_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload System Verification Result
        id: upload-system-ver
        uses: coauthor-app/capture-action@v0.0.1
        with:
          evidence: 'system-verification'
          type: 'bdd'
          format: 'cucumber+ndjson'
          hostname: ${{vars.UPLOAD_JOB}}
          path: 'reports/bdd/**'
      - name: Upload Item Verification Result
        id: upload-item-ver
        uses: coauthor-app/capture-action@v0.1.0-beta
        with:
          evidence: 'item-verification'
          type: 'bdd'
          format: 'cucumber+ndjson'
          hostname: ${{vars.UPLOAD_JOB}}
          path: 'reports/bdd/**'

      - name: Upload SBOM
        id: upload-sbom
        uses: coauthor-app/capture-action@v0.1.0-beta
        with:
          evidence: 'cybersecurity'
          type: 'sbom'
          switem: 'moduleA'
          format: 'cyclonedx'
          hostname: 'nll3vb6d1l.execute-api.eu-west-2.amazonaws.com'
          path: 'reports/sbom/**'
