on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  upload_job:
    runs-on: ubuntu-latest
    name: Upload Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Item Verification Result
        id: upload-item-ver-core
        uses: coauthor-app/capture-action@v1
        with:
          evidence: 'item-verification'
          type: 'test'
          switem: 'module-core'
          format: 'junit'
          hostname: ${{vars.UPLOAD_JOB}}
          path: 'reports/item/core/**'

      - name: Upload Item Verification Result
        id: upload-item-ver-data
        uses: coauthor-app/capture-action@v1
        with:
          evidence: 'item-verification'
          type: 'test'
          switem: 'module-data'
          format: 'junit'
          hostname: ${{vars.UPLOAD_JOB}}
          path: 'reports/item/data/**'

      - name: Upload Item Verification Result
        id: upload-item-ver-moduleA
        uses: coauthor-app/capture-action@v1
        with:
          evidence: 'item-verification'
          type: 'test'
          switem: 'moduleA'
          format: 'junit'
          hostname: ${{vars.UPLOAD_JOB}}
          path: 'reports/item/core/**'

      - name: Upload System Verification Result
        id: upload-sys-ver-moduleA
        uses: coauthor-app/capture-action@v1
        with:
          evidence: 'system-verification'
          type: 'test'
          format: 'cucumber+ndjson'
          hostname: ${{vars.UPLOAD_JOB}}
          path: 'reports/bdd/**'

      - name: Upload SBOM moduleA
        id: upload-sbom-moduleA
        uses: coauthor-app/capture-action@v1
        with:
          evidence: 'cybersecurity'
          type: 'sbom'
          switem: 'moduleA'
          format: 'cyclonedx'
          hostname: ${{vars.UPLOAD_JOB}}
          path: 'reports/sbom/moduleA.bom.json'

      - name: Upload SBOM module-core
        id: upload-sbom-module-core
        uses: coauthor-app/capture-action@v1.0.1
        with:
          evidence: 'cybersecurity'
          type: 'sbom'
          switem: 'module-core'
          format: 'cyclonedx'
          hostname: ${{vars.UPLOAD_JOB}}
          path: 'reports/sbom/module-core.bom.json'

      - name: Upload SBOM module-data
        id: upload-sbom-module-data
        uses: coauthor-app/capture-action@v1
        with:
          evidence: 'cybersecurity'
          type: 'sbom'
          switem: 'module-data'
          format: 'cyclonedx'
          hostname: ${{vars.UPLOAD_JOB}}
          path: 'reports/sbom/module-data.bom.json'

      - name: Wrong upload setting
        id: wrong-upload-setting
        uses: coauthor-app/capture-action@v1
        with:
          evidence: 'system-verification'
          type: 'sbom'
          format: 'cyclonedx'
          hostname: ${{vars.UPLOAD_JOB}}
          path: 'reports/sbom/module-data.bom.json'
