on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  upload_job:
    runs-on: ubuntu-latest
    name: Upload Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload System Verification Result
        id: upload-system-ver
        uses: coauthor-app/capture-action@v1.0.0
        with:
          evidence: 'system-verification'
          type: 'bdd'
          format: 'cucumber+ndjson'
          hostname: ${{vars.UPLOAD_JOB}}
          path: 'reports/bdd/**'
      - name: Upload Item Verification Result
        id: upload-item-ver
        uses: coauthor-app/capture-action@v1.0.0
        with:
          evidence: 'item-verification'
          type: 'bdd'
          format: 'cucumber+ndjson'
          hostname: ${{vars.UPLOAD_JOB}}
          path: 'reports/bdd/**'

      - name: Upload SBOM moduleA
        id: upload-sbom-moduleA
        uses: coauthor-app/capture-action@v1.0.0
        with:
          evidence: 'cybersecurity'
          type: 'sbom'
          switem: 'moduleA'
          format: 'cyclonedx'
          hostname: ${{vars.UPLOAD_JOB}}
          path: 'reports/sbom/**'

      - name: Upload SBOM module-core
        id: upload-sbom-module-core
        uses: coauthor-app/capture-action@v1.0.0
        with:
          evidence: 'cybersecurity'
          type: 'sbom'
          switem: 'module-core'
          format: 'cyclonedx'
          hostname: ${{vars.UPLOAD_JOB}}
          path: 'reports/sbom/**'
