on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  upload_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: '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'

      - name: Upload Job Testing
        id: hello-from-test-webhook-repo
        uses: coauthor-app/capture-action@main
        with:
          evidence: 'system-verification'
          type: 'BDD'
          format: 'serenity'
          hostname: 'hqcy8arp5d.execute-api.eu-west-2.amazonaws.com'
          path: 'reports/**'
